# region Project-wide Gradle settings.
# IDE (e.g. Android Studio) users:
# Gradle settings configured through the IDE *will override*
# any settings specified in this file.
# For more details on how to configure your build environment visit
# http://www.gradle.org/docs/current/userguide/build_environment.html

# Gradle

# Specifies the JVM arguments used for the daemon process.
# The setting is particularly useful for tweaking memory settings.
org.gradle.jvmargs=-Xmx3072m -Dfile.encoding=UTF-8

org.gradle.caching=true

org.gradle.configuration-cache=true

# Kotlin

# Kotlin code style for this project: "official" or "obsolete":
kotlin.code.style=official

kotlin.daemon.jvmargs=-Xmx2048M

# Android

# Enables namespacing of each library's R class so that its R class includes only the
# resources declared in the library itself and none from the library's dependencies,
# thereby reducing the size of the R class for that library
android.nonTransitiveRClass=true

# AndroidX package structure to make it clearer which packages are bundled with the
# Android operating system, and which are packaged with your app's APK
# https://developer.android.com/topic/libraries/support-library/androidx-rn
android.useAndroidX=true

# Publication info
POM_NAME=TextToSpeechKt
POM_DESCRIPTION=Text-to-Speech library for Kotlin Multiplatform. Supports targets Android, iOS, macOS and browser (js and wasmJs).
POM_INCEPTION_YEAR=2020
POM_URL=https://github.com/Marc-JB/TextToSpeechKt

POM_LICENSE_NAME=The MIT License (MIT)
POM_LICENSE_URL=https://opensource.org/licenses/MIT
POM_LICENSE_DIST=repo

POM_SCM_URL=https://github.com/Marc-JB/TextToSpeechKt/
POM_SCM_CONNECTION=scm:git:git://github.com/Marc-JB/TextToSpeechKt.git
POM_SCM_DEV_CONNECTION=scm:git:ssh://git@github.com/Marc-JB/TextToSpeechKt.git

POM_DEVELOPER_ID=Marc-JB
POM_DEVELOPER_NAME=Marc
POM_DEVELOPER_URL=https://marc-apps.nl
