[versions]
android-gradlePlugin = "8.13.0"
androidx-annotation = "1.9.1"

freetts = "1.2.2"

jetbrains-compose = "1.9.1"
jetbrains-dokka = "2.1.0"

kotlin = "2.2.20"
kotlinx-browser = "0.5.0"
kotlinx-coroutines = "1.10.2"

mavenPublishing = "0.34.0"

[libraries]
androidx-annotation = { module = "androidx.annotation:annotation", version.ref = "androidx-annotation" }

freetts = { module = "net.sf.sociaal:freetts", version.ref = "freetts" }

jetbrains-dokka-plugins-androidDocumentation = { module = "org.jetbrains.dokka:android-documentation-plugin", version.ref = "jetbrains-dokka" }
jetbrains-dokka-plugins-versioning = { module = "org.jetbrains.dokka:versioning-plugin", version.ref = "jetbrains-dokka" }

kotlinx-browser = { module = "org.jetbrains.kotlinx:kotlinx-browser", version.ref = "kotlinx-browser" }
kotlinx-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }

[plugins]
android-application = { id = "com.android.application", version.ref = "android-gradlePlugin" }
android-library-kmp = { id = "com.android.kotlin.multiplatform.library", version.ref = "android-gradlePlugin" }
android-lint = { id = "com.android.lint", version.ref = "android-gradlePlugin" }

jetbrains-compose = { id = "org.jetbrains.compose", version.ref = "jetbrains-compose" }
jetbrains-compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }

jetbrains-dokka = { id = "org.jetbrains.dokka", version.ref = "jetbrains-dokka" }

kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }

mavenPublishing = { id = "com.vanniktech.maven.publish", version.ref = "mavenPublishing" }
