name: Gradle deployment

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy-lib:
    runs-on: ubuntu-latest
    steps:

      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v2

      # Set up JDK
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      # Cache
      - uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: ${{ runner.os }}-gradle-

      # Permissions for Gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # Build
      - name: Build with Gradle
        run: ./gradlew build

      # Deploy
      - name: Deploy with Gradle
        run: ./gradlew publish
        env:
          USERNAME: github-actions
          TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deploy-docs:
    runs-on: ubuntu-latest
    steps:

      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v2

      # Set up JDK
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      # Cache
      - uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: ${{ runner.os }}-gradle-

      # Permissions for Gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # Generate docs
      - name: Generate docs with Gradle & Dokka
        run: ./gradlew dokkaHtml

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: ./build/dokka/html/
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
