name: Gradle deployment

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy-lib:
    runs-on: ubuntu-latest
    timeout-minutes: 8
    steps:

      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v2

      # Set up JDK
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      # Cache
      - uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: ${{ runner.os }}-gradle-

      # Permissions for Gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # Build
      - name: Build with Gradle
        run: ./gradlew :tts:build

      # Deploy
      - name: Deploy with Gradle
        run: ./gradlew :tts:publish
        env:
          GPR_USER: github-actions
          GPR_KEY: ${{ secrets.GITHUB_TOKEN }}
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          GPG_SIGNING_KEY: ${{ secrets.GPG_SIGNING_KEY }}
          GPG_SIGNING_PASSWORD: ${{ secrets.GPG_SIGNING_PASSWORD }}

      # Move artifacts
      - name: Move artifacts
        run: |
          mkdir out
          mkdir out/browser
          cp ./tts/build/distributions/tts.js ./out/browser/tts.js
          cp ./tts/build/distributions/tts.js.map ./out/browser/tts.js.map
          cp ./tts/typings/tts.d.ts ./out/browser/tts.d.ts
          mkdir out/android
          cp ./tts/build/outputs/aar/tts-debug.aar ./out/android/tts-debug.aar
          cp ./tts/build/outputs/aar/tts-release.aar ./out/android/tts-release.aar

      # Upload artifacts
      - uses: actions/upload-artifact@v2
        with:
          name: TextToSpeechKt (Browser)
          path: ./out/browser/tts.*
          if-no-files-found: error

      - uses: actions/upload-artifact@v2
        with:
          name: TextToSpeechKt (Android)
          path: ./out/android/tts-*.aar
          if-no-files-found: error

  deploy-docs:
    runs-on: ubuntu-latest
    timeout-minutes: 8
    steps:

      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v2

      # Set up JDK
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      # Cache
      - uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: ${{ runner.os }}-gradle-

      # Permissions for Gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # Generate docs
      - name: Generate docs with Gradle & Dokka
        run: ./gradlew :tts:dokkaHtml

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: ./tts/build/dokka/html/
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
